export const THROWS = "/icons/Home_icons/throws.svg"
export const STATS = "/icons/Home_icons/stats.svg"
export const INFO = "/icons/Home_icons/info.svg"
export const ACTIONS = "/icons/Home_icons/actions.svg"
export const LEVELUP = "/icons/Home_icons/levelup.svg"
export const EQUIPMENT = "/icons/Home_icons/equipment.svg"