export const STRENGTH = "/icons/Stats_icons/str.svg"
export const DEXTERITY = "/icons/Stats_icons/dex.svg"
export const CONSTITUTION = "/icons/Stats_icons/cons.svg"
export const INTELLIGENCE = "/icons/Stats_icons/int.svg"
export const WISDOM = "/icons/Stats_icons/wis.svg"
export const CHARISMA = "/icons/Stats_icons/cha.svg"