export const MINUS = "/icons/Utility/minus.svg"
export const PLUS = "/icons/Utility/plus.svg"
export const SELMINUS = "/icons/Utility/selminus.svg"
export const SELPLUS = "/icons/Utility/selplus.svg"
export const NEXT = "/icons/Utility/next.svg"
export const PREVIOUS = "/icons/Utility/previous.svg"
export const CONFIRM = "/icons/Utility/confirm.svg"